release2.0.0-beta.4

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -3,13 +3,6 @@ version: 0.2
 phases:
   install:
     commands:
-      - echo 'Beginning production build'
-      - CURRENT_PUBLISHED_VERSION=$(npm info adjs version)
-      - if [ -z $CURRENT_PUBLISHED_VERSION ]; then echo "Could not find latest published version. Exiting build."; exit 1; fi
-      - LOCAL_VERSION=$(node -e "console.log(require('./package.json').version)")
-      - if [ -z $LOCAL_VERSION ]; then echo "Version is missing from package.json. Exiting build."; exit 1; fi
-      - if [ $LOCAL_VERSION = $CURRENT_PUBLISHED_VERSION ]; then echo "Version is unchanged. Exiting build without error."; exit 0; fi
-      - npm install -g npm@latest
       - npm install
   pre_build:
     commands:
@@ -17,9 +10,19 @@ phases:
       - npm run test
   build:
     commands:
-      - sudo apt-get update
-      - sudo apt-get install build-essential -y
-      - wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-1.5.tar.gz && tar xzf jq-1.5.tar.gz && cd jq-1.5 && ./configure && make && make install && cd ..
-      - npm config set '//registry.npmjs.org/:_authToken' $(aws ssm get-parameter --name npm-publish-token | jq '.Parameter.Value')
-      - npm run release
-
+      - echo 'Verifying npm publish is required'
+      - CURRENT_PUBLISHED_VERSION=$(npm info adjs version)
+      - if [ -z $CURRENT_PUBLISHED_VERSION ]; then echo "Could not find latest published version. Exiting build."; exit 1; fi
+      - LOCAL_VERSION=$(node -e "console.log(require('./package.json').version)")
+      - if [ -z $LOCAL_VERSION ]; then echo "Version is missing from package.json. Exiting build."; exit 1; fi
+      - |
+        if [ $LOCAL_VERSION = $CURRENT_PUBLISHED_VERSION ]; then
+          echo "Version is unchanged. NPM publish is not required."
+        else
+          echo "New version detected. Publishing to NPM."
+          sudo apt-get update
+          sudo apt-get install build-essential -y
+          wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-1.5.tar.gz && tar xzf jq-1.5.tar.gz && cd jq-1.5 && ./configure && make && make install && cd ..
+          npm config set '//registry.npmjs.org/:_authToken' $(aws ssm get-parameter --name npm-publish-token | jq '.Parameter.Value')
+          npm run release
+        fi
